baseURL = "https://example.com/"
languageCode = "en-us"
title = "BlankPage Anime"
paginate = 15
enableRobotsTXT = true
[params]
  description = "Simple anime recommendations"
  author = "BlankPage Anime Team"
[outputs]
  home = ["HTML", "RSS"]
[sitemap]
  changefreq = "daily"
  priority = 0.8
[markup.goldmark.renderer]
  unsafe = true
